export const Auth = {
  LOGIN_USER_SUCCESS: 'auth/LOGIN_USER_SUCCESS',
  LOGIN_USER_FAIL: 'auth/LOGIN_USER_FAIL',
  REGISTER_USER_SUCCESS: 'auth/REGISTER_USER_SUCCESS',
  REGISTER_USER_FAIL: 'auth/REGISTER_USER_FAIL',
  CREATE_GUEST_SESSION_SUCCESS: 'auth/CREATE_GUEST_SESSION_SUCCESS',
  CREATE_GUEST_SESSION_FAIL: 'auth/CREATE_GUEST_SESSION_FAIL',
  ATTEMPING: 'ATTEMPING',
  USER_LOADED: 'auth/USER_LOADED',
  USER_INFO_UPDATE: 'auth/USER_INFO_UPDATE',
  UPDATE_INTERESTED: 'auth/UPDATE_INTERESTED',
  LOG_OUT: 'auth/LOG_OUT',
};

export const EVENT = {
  SET_EVENT_DATA: 'SET_EVENT_DATA',
  ADD_EVENT_DATA: 'ADD_EVENT_DATA',
};
export const Notication = {
  RECEIVE_NEW: 'notif/RECEIVE_NEW',
  SEEN: 'notif/SEEN',
  UPDATE_COUNT: 'notif/UPDATE_COUNT',
};
export const MAIN = {
  SET_CATEGORIES: 'SET_CATEGORIES',
};
